#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-hamcrest
Version  : 1.3
Release  : 3
URL      : https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
Source0  : https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
Source1  : https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
Source2  : https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.pom
Source3  : https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Source4  : https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-hamcrest-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-hamcrest package.
Group: Data

%description data
data components for the mvn-hamcrest package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-parent/1.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/hamcrest/hamcrest-parent/1.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.pom
/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
/usr/share/java/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
/usr/share/java/.m2/repository/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
